# -*- coding: utf-8 -*-
{
    'name': 'Education Management System',
    'version': '17.0',
    'summary': '''EMS,
        educational management system,
        student,
        school,
        teacher,
        subject,
        academic year,
        marks,
        exams,
        levels,
        division,
        academic,
        class,''',
    'description':
        '''EMS (Education Management System) is a comprehensive Odoo module designed to streamline educational institutions' administrative and academic operations. 
        It offers a user-friendly interface in both English and Arabic languages,
        empowering efficient management of students, faculty, courses, and academic records.''',
    'category': 'Generic Modules/Human Resources',
    'author': "Neoteric Hub",
    'company': 'Neoteric Hub',
    'price': 0,
    'currency': 'USD',
    'website': "https://www.neoterichub.com",
    'depends': ['base', 'mail', 'board'],  # 'web_domain_field'
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/scheduled_data.xml',
        'wizard/multiple_marks_wizard_view.xml',
        'wizard/multiple_academic_records_wizard_view.xml',
        'views/level.xml',
        'views/education_record.xml',
        'views/department.xml',
        'views/sub_department.xml',
        'views/subject.xml',
        'views/marks.xml',
        'views/student_student_view.xml',
        'views/teacher_teacher_view.xml',
        'views/qualification_student_view.xml',
        'views/settings_views.xml',
        'views/dashboard.xml',
        'views/menus.xml',
        'reports/student_data_report.xml',
        'reports/student_report.xml',
        'reports/proof_of_registration_report.xml',
        'reports/commit_number_report_template.xml',
        'reports/sitting_number_report_template.xml',
        'reports/classes_number_report_template.xml',
        'reports/student_card.xml',
        'reports/college_degree.xml',
    ],

    'assets': {
        'web.assets_backend': [
            '/nthub_ems/static/src/js/mark_tree_extend.js',
            '/nthub_ems/static/src/js/academic_records_tree_extend.js',
            '/nthub_ems/static/src/xml/mark_tree_button.xml',
            '/nthub_ems/static/src/xml/academic_records_tree_button.xml',
        ]
    },
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
